name: Update Repo Badge

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecuta este script una vez al día
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Fetch repository count
        id: repo-count
        run: |
          REPO_COUNT=$(curl -s https://api.github.com/users/Aritz-Garcia | jq -r .public_repos)
          echo "REPO_COUNT=$REPO_COUNT" >> $GITHUB_ENV
          echo "::set-output name=REPO_COUNT::$REPO_COUNT"

      - name: Read current badge count
        id: current-badge
        run: |
          CURRENT_COUNT=$(grep -oP '(?<=badge/)\d+' README.md)
          echo "::set-output name=CURRENT_COUNT::$CURRENT_COUNT"

      - name: Update README if needed
        if: steps.repo-count.outputs.REPO_COUNT != steps.current-badge.outputs.CURRENT_COUNT
        run: |
          sed -i "/<!-- repo_count_starts -->/,/<!-- repo_count_ends -->/c <!-- repo_count_starts -->\n![](https://img.shields.io/badge/${{ env.REPO_COUNT }}-%20?&style=for-the-badge&logo=github&logoColor=FFFFFF&label=REPOSITORIOS&color=37ae6c)\n<!-- repo_count_ends -->" README.md
          git config --global user.email aritz2030@gmail.com
          git config --global user.name "Aritz-Garcia"
          git add README.md
          git commit -m "Update README with the latest public repo count: ${{ env.REPO_COUNT }}"
          git push
