name: Update Repo Badge

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecuta este script una vez al día
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Fetch repository count
        run: |
          REPO_COUNT=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/users/${{ github.repository_owner }} | jq -r .public_repos)
          echo "REPO_COUNT=$REPO_COUNT" >> $GITHUB_ENV

      - name: Read current badge count
        run: |
          CURRENT_COUNT=$(grep -oP '(?<=badge/)\d+' README.md)
          echo "CURRENT_COUNT=$CURRENT_COUNT" >> $GITHUB_ENV

      - name: Update README if needed
        if: env.REPO_COUNT != env.CURRENT_COUNT
        run: |
          sed -i "/<!-- repo_count_starts -->/,/<!-- repo_count_ends -->/c<!-- repo_count_starts -->\n![](https://img.shields.io/badge/${{ env.REPO_COUNT }}-%20?&style=for-the-badge&logo=github&logoColor=FFFFFF&label=REPOSITORIOS&color=37ae6c)<!-- repo_count_ends -->" README.md
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with the latest public repo count: ${{ env.REPO_COUNT }}"
          git push

